languageCode = "ja-JP"
title = "Play2 + Slick / ScalikeJDBCハンズオン"
theme = "hugo_theme_robust"
metadataformat = "yaml"
canonifyurls = true
uglyurls = true
publishDir = "docs"
copyright = "BizReach, Inc"
